// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/DarkAIRenderMusicPlayer-fEqdJu/App.tsx": () => import("../components/mockups/templates/DarkAIRenderMusicPlayer-fEqdJu/App.tsx"),
  "./components/mockups/templates/MissionControlBentoDashboard-K_pnE0/Dashboard.tsx": () => import("../components/mockups/templates/MissionControlBentoDashboard-K_pnE0/Dashboard.tsx"),
  "./components/mockups/templates/NeonHorizonsTravelCarousel-ZQzRp7/App.tsx": () => import("../components/mockups/templates/NeonHorizonsTravelCarousel-ZQzRp7/App.tsx"),
  "./components/mockups/templates/OrangePortraitEventPoster-hfQpod/DeepOrangePoster.tsx": () => import("../components/mockups/templates/OrangePortraitEventPoster-hfQpod/DeepOrangePoster.tsx")
};
